#####
# Author: TheUnkn0wn1
# File: serialTest.py
# Function: Establish and handle serial comms between Pi and RoboClaw
###

'''Import dependant libs'''
import platform # for version check
import serial #Common pySerial library
from zlib import crc32 as crc #for CRC check, neccessary for communication



#import RPi.GPIO as gpio #renaming because I hate caps...

class mySerial():
	"""class that handles serial communication with the RoboClaw"""
	port = "/dev/ttyAMA0" #the comport on the Pi itself
	tx = 8 	#Red wire	#gpio pins in use here, might be useful later
	rx = 10	#purple		#gpio pins in use here, might be useful later
	
	def __init__(self, arg):	#tbh this stuff was auto-generated by my editor...
		super(mySerial, self).__init__()	#tbh this stuff was auto-generated by my editor...
		self.arg = arg	#tbh this stuff was auto-generated by my editor...
	def prepareSerial(self):
		"""Prepare the serial connection for use, returns serial object"""
		try:
			ser = serial.Serial(self.port,38400,timeout=5) #creates serial object 'ser' for usage
		except Exception as error: #because i want to see any exception that is thrown right now
			print("mySerial::prepareSerial\t Encountered an error creating serial object!")
			#print(type(error))	#redundant
			print(error)
			ser.open()
